project_id = "vwtyzvppbafbcpdbgxgj"

[functions.gmail-auth]
verify_jwt = false

[functions.gmail-callback]
verify_jwt = false

[functions.gmail-sync]
verify_jwt = false

[functions.microsoft-auth]
verify_jwt = false

[functions.microsoft-callback]
verify_jwt = false

[functions.microsoft-sync]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
